const dummyChamas = [
  {
    id: 1,
    name: "Family First Savings",
    description: "A group committed to saving for family milestones and emergencies.",
    contributionCycle: "Monthly",
    depositAmount: "0.5 ETH",
    contributionAmount: "0.1 ETH",
    penaltyPercentage: "5%",
    maxMembers: 8,
  },
  {
    id: 2,
    name: "Friends United",
    description: "Pooling funds to create unforgettable memories and support each other.",
    contributionCycle: "Weekly",
    depositAmount: "0.3 ETH",
    contributionAmount: "0.05 ETH",
    penaltyPercentage: "3%",
    maxMembers: 10,
  },
  {
    id: 3,
    name: "Startup Dream",
    description: "A dedicated group saving for that breakthrough startup idea.",
    contributionCycle: "Daily",
    depositAmount: "1 ETH",
    contributionAmount: "0.2 ETH",
    penaltyPercentage: "10%",
    maxMembers: 5,
  },
  {
    id: 4,
    name: "Community Growth",
    description: "Investing in local projects to boost community development.",
    contributionCycle: "Monthly",
    depositAmount: "0.7 ETH",
    contributionAmount: "0.15 ETH",
    penaltyPercentage: "7%",
    maxMembers: 12,
  },
  {
    id: 5,
    name: "Holiday Fund",
    description: "Saving together for that much-needed vacation or festive celebration.",
    contributionCycle: "Weekly",
    depositAmount: "0.4 ETH",
    contributionAmount: "0.08 ETH",
    penaltyPercentage: "4%",
    maxMembers: 8,
  },
  {
    id: 6,
    name: "Education Fund",
    description: "A focused group aiming to support educational pursuits and scholarships.",
    contributionCycle: "Monthly",
    depositAmount: "0.6 ETH",
    contributionAmount: "0.12 ETH",
    penaltyPercentage: "6%",
    maxMembers: 10,
  },
  {
    id: 7,
    name: "Entrepreneur Collective",
    description: "Pooling resources to launch new ventures and support local businesses.",
    contributionCycle: "Monthly",
    depositAmount: "0.8 ETH",
    contributionAmount: "0.2 ETH",
    penaltyPercentage: "8%",
    maxMembers: 7,
  },
  {
    id: 8,
    name: "Future Builders",
    description: "Saving together for long-term wealth creation and real estate investments.",
    contributionCycle: "Weekly",
    depositAmount: "1.2 ETH",
    contributionAmount: "0.25 ETH",
    penaltyPercentage: "9%",
    maxMembers: 6,
  },
];

export default dummyChamas;
